/* Browser implementation of catalog/reader.py. Files never leave this tab. */
const state={files:[],docs:[],issues:[],log:[],pivot:50};
const $=id=>document.getElementById(id); const norm=v=>String(v??'').normalize('NFC').replace(/\s+/g,' ').trim();
const simple=v=>norm(v).normalize('NFD').toLowerCase().replace(/[\u0300-\u036f]/g,'').replace('đ','d');
const colName=n=>{let s='';while(n){let r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s};
function log(s){state.log.push(new Date().toLocaleTimeString()+'  '+s);$('logText').textContent=state.log.join('\n')}
function updateHint(){let p=+$('pivot').value||50;state.pivot=p;$('pivotHint').textContent=`00–${String(p-1).padStart(2,'0')} → 2000–${2000+p-1}; ${String(p).padStart(2,'0')}–99 → ${1900+p}–1999`}
function validSheet(ws,name){let rows=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''});let title=[];for(let i=0;i<Math.min(rows.length,80);i++){let r=rows[i]||[];let b=norm(r[1]),c=norm(r[2]);if(simple(b).includes('ten tai lieu')&&simple(c).includes('ma so')){let t=simple(title.join(' '));return /iso\s*-\s*pr\s*-\s*0001\s*\/\s*re04/.test(t)|| (t.includes('danh muc tai lieu noi bo')&&t.includes('internal documents list'))}title.push(...r.filter(Boolean));}return false}
function inferKind(name,rows){let code='';for(const r of rows){if(r[2]){code=norm(r[2]);break}}return /.+\/RE\d{2}$/i.test(code)||simple(name).includes('bieu')?'BIEU MAU':'HDCV'}
async function addFiles(files){for(const file of files){if(state.files.some(x=>x.file.name===file.name&&x.file.size===file.size))continue;try{let wb=XLSX.read(await file.arrayBuffer(),{cellFormula:true,cellNF:false});let sheets=[];for(const name of wb.SheetNames){if(/(^|[^a-z0-9])huy([^a-z0-9]|$)/i.test(simple(name))||wb.Workbook?.Sheets?.find(s=>s.name===name)?.Hidden)continue;let ws=wb.Sheets[name],rows=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''});if(validSheet(ws,name))sheets.push({name,kind:inferKind(name,rows),checked:['HDCV','BIEU MAU'].includes(name.toUpperCase())});}state.files.push({file,wb,sheets});log(`Đã thêm ${file.name} (${sheets.length} sheet hợp lệ)`)}catch(e){log(`LỖI ${file.name}: ${e.message}`)}}renderFiles()}
function renderFiles(){let el=$('files');el.innerHTML='';if(!state.files.length){el.innerHTML='<div class="empty">Chưa có file. Bấm “Thêm file Excel” để bắt đầu.</div>';return}state.files.forEach((f,fi)=>{let box=document.createElement('div');box.className='file';box.innerHTML=`<div class="file-head"><strong>${esc(f.file.name)}</strong><button data-remove="${fi}">Xóa file</button></div>`;f.sheets.forEach((s,si)=>{let row=document.createElement('div');row.className='sheet';row.innerHTML=`<input type="checkbox" ${s.checked?'checked':''} data-check="${fi},${si}"><label>${esc(s.name)}</label><select data-kind="${fi},${si}"><option ${s.kind==='HDCV'?'selected':''}>HDCV</option><option ${s.kind==='BIEU MAU'?'selected':''}>BIEU MAU</option></select>`;box.append(row)});el.append(box)});el.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.files.splice(+b.dataset.remove,1);renderFiles()});el.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>state.files[x.dataset.check.split(',')[0]].sheets[x.dataset.check.split(',')[1]].checked=x.checked);el.querySelectorAll('[data-kind]').forEach(x=>x.onchange=()=>state.files[x.dataset.kind.split(',')[0]].sheets[x.dataset.kind.split(',')[1]].kind=x.value)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function parseRevision(raw,source,code,issues){raw=String(raw);if(raw.startsWith('!FORMULA:')){issues.push(issue(source,code,'Ô lịch sử có công thức; cần chuyển thành dữ liệu xác nhận trong file nguồn.'));return null}let ms=[...raw.matchAll(/(?<!\d)(\d{1,2})\s*[\/.\-]\s*(\d{1,2})\s*[\/.\-]\s*(\d{2,4})(?!\d)/g)];if(ms.length!==1){issues.push(issue(source,code,'Không xác định được duy nhất một ngày trong ô: '+raw));return {raw,revision:'',issued:null,detail:''}}let m=ms[0],y=+m[3];if(m[3].length===2)y+=y<state.pivot?2000:1900;let issued=null;let d=new Date(y,+m[2]-1,+m[1]);if(d.getFullYear()===y&&d.getMonth()===+m[2]-1&&d.getDate()===+m[1])issued=d;else issues.push(issue(source,code,'Ngày không hợp lệ: '+m[0]));let rest=(raw.slice(0,m.index)+raw.slice(m.index+m[0].length)).trim(),rm=rest.match(/^(\d+(?:\s*\/\s*\d+)?)(?=\s|\(|$)/),revision=rm?rm[1].replace(/\s/g,''):'',detail=rm?rest.slice(rm[0].length).trim():rest;if(!revision)issues.push(issue(source,code,'Thiếu hoặc không nhận diện được lần ban hành: '+raw));return {raw,revision,issued,detail,source}}
function issue(s,c,message,level='LỖI'){return {level,file:s.file,sheet:s.sheet,cell:s.cell,code:c,message}}
function scanSheet(f,s){let ws=f.wb.Sheets[s.name],rows=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''}),header=-1,end=0;for(let i=0;i<rows.length;i++){let r=rows[i];if(simple(r[1]).includes('ten tai lieu')&&simple(r[2]).includes('ma so')){header=i;for(let c=4;c<r.length;c++)if(simple(r[c]).includes('ghi chu')){end=c;break}break}}if(header<0||!end){state.issues.push(issue({file:f.file.name,sheet:s.name,cell:''},'','Không nhận diện được tiêu đề cột B/C hoặc ranh giới cột Ghi chú.'));return[]}let docs=[],active=null;for(let i=header+1;i<rows.length;i++){let r=rows[i],name=norm(r[1]),code=norm(r[2]).toUpperCase(),history=[];for(let c=3;c<end;c++)if(norm(r[c]))history.push(parseRevision(norm(r[c]),{file:f.file.name,sheet:s.name,cell:colName(c+1)+(i+1),start_row:i+1},code,state.issues));if(name&&code){active={code,name,kind:s.kind,sources:[{file:f.file.name,sheet:s.name,start_row:i+1}],history:[],notes:[]};docs.push(active)}else if(!name&&!code&&history.length&&!active){state.issues.push(issue({file:f.file.name,sheet:s.name,cell:'D'+(i+1)},'','Dòng tiếp nối không có tài liệu phía trước.'));continue}else if(!name&&!code&&!history.length)continue;else if((name&&!code)||(!name&&code)){state.issues.push(issue({file:f.file.name,sheet:s.name,cell:'B'+(i+1)},code,'Thiếu tên hoặc mã tài liệu; không có vùng gộp phù hợp.'));active=null;continue}if(active)active.history.push(...history);for(let c=end;c<r.length;c++)if(norm(r[c]))active.notes.push({text:norm(r[c]),file:f.file.name,sheet:s.name,cell:colName(c+1)+(i+1)})}return docs}
function consolidate(items){let grouped=new Map();for(let d of items){if(!d.history.length)state.issues.push(issue(d.sources[0],d.code,'Tài liệu không có lịch sử ban hành.'));let old=grouped.get(d.code);if(old){if(old.name.toLowerCase()!==d.name.toLowerCase())state.issues.push(issue(d.sources[0],d.code,'Cùng mã nhưng khác tên: '+old.name+' / '+d.name));if(old.kind!==d.kind)state.issues.push(issue(d.sources[0],d.code,'Cùng mã xuất hiện ở cả HDCV và BIEU MAU.'));old.history.push(...d.history);old.sources.push(...d.sources);old.notes.push(...d.notes)}else grouped.set(d.code,d)}for(let d of grouped.values()){let byRev=new Map(),unique=[];for(let h of d.history){let key=[h.revision,h.issued?.toISOString(),norm(h.detail),h.raw].join('|');if(h.revision&&byRev.has(h.revision)&&byRev.get(h.revision)!==key)state.issues.push(issue(h.source,d.code,`Lần ban hành ${h.revision} có ngày/nội dung khác nhau.`));byRev.set(h.revision,key);if(!unique.some(x=>x._key===key)){h._key=key;unique.push(h)}}d.history=unique;let valid=unique.filter(h=>h.issued&&h.revision);d.latest=valid.sort((a,b)=>b.issued-a.issued||b.revision.localeCompare(a.revision,undefined,{numeric:true}))[0];if(d.sources.length>1){let locations=d.sources.map(s=>`${s.file} / ${s.sheet} / C${s.start_row}`).join('; ');state.issues.push(issue(d.sources[0],d.code,`Đã hợp nhất ${d.sources.length} mục nguồn cùng mã: ${locations}.`,'CẢNH BÁO'))}}return [...grouped.values()].sort((a,b)=>a.code.localeCompare(b.code))}
async function scan(){state.docs=[];state.issues=[];let all=[];for(let f of state.files)for(let s of f.sheets.filter(x=>x.checked)){log(`Đang đọc ${f.file.name} / ${s.name}`);all.push(...scanSheet(f,s))}state.docs=consolidate(all);if(!state.docs.length)state.issues.push(issue({file:'',sheet:'',cell:''},'','Không tìm thấy tài liệu; không được thay dữ liệu.'));$('summary').textContent=`${state.files.length} file | ${state.docs.length} mã duy nhất | ${state.issues.filter(x=>x.level==='LỖI').length} lỗi | ${state.issues.filter(x=>x.level==='CẢNH BÁO').length} cảnh báo`;log('Đọc xong. '+(state.issues.some(x=>x.level==='LỖI')?'Cần sửa lỗi trước khi xuất dữ liệu.':'Dữ liệu đủ điều kiện kiểm tra.'));renderAll()}
function renderAll(){let q=$('search').value.toLowerCase(),k=$('kind').value,ds=state.docs.filter(d=>(!q||d.code.toLowerCase().includes(q)||d.name.toLowerCase().includes(q))&&(k==='Tất cả loại'||d.kind===k));$('catalogTable').innerHTML='<thead><tr><th>Mã tài liệu</th><th>Tên tài liệu</th><th>Lần BH</th><th>Ngày BH</th><th>Loại</th><th>File</th><th>Sheet</th><th>Dòng</th></tr></thead><tbody>'+ds.map((d,i)=>{let h=d.latest||{},s=(h.source||d.sources[0]);return `<tr data-doc="${state.docs.indexOf(d)}"><td>${esc(d.code)}</td><td class="wrap">${esc(d.name)}</td><td>${esc(h.revision||'')}</td><td>${h.issued?h.issued.toLocaleDateString('vi-VN'):''}</td><td>${d.kind}</td><td>${esc(s.file)}</td><td>${esc(s.sheet)}</td><td>${s.start_row||''}</td></tr>`}).join('')+'</tbody>';let lv=$('issueLevel').value,is=state.issues.filter(x=>lv==='Tất cả'||x.level===lv);$('issueTable').innerHTML='<thead><tr><th>Mức</th><th>File</th><th>Sheet</th><th>Ô</th><th>Mã</th><th>Nội dung</th></tr></thead><tbody>'+is.map(x=>`<tr><td class="${x.level==='LỖI'?'level-error':'level-warning'}">${x.level}</td><td>${esc(x.file)}</td><td>${esc(x.sheet)}</td><td>${x.cell}</td><td>${esc(x.code)}</td><td class="wrap">${esc(x.message)}</td></tr>`).join('')+'</tbody>'}
function csv(headers,rows){let q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return [headers,...rows].map(r=>r.map(q).join(',')).join('\r\n')}
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCatalog(){let rows=state.docs.map(d=>{let h=d.latest||{},s=h.source||d.sources[0];return[d.code,d.name,d.kind,h.revision||'',h.issued?.toISOString().slice(0,10)||'',s.file,s.sheet,s.start_row]});let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Mã','Tên','Loại','Lần BH','Ngày BH','File','Sheet','Dòng'],...rows]),'Danh mục');download('danh_muc_xem_truoc.xlsx',XLSX.write(wb,{bookType:'xlsx',type:'array'}),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}
function exportCatalogCsv(){let rows=state.docs.map(d=>{let h=d.latest||{},s=h.source||d.sources[0];return[d.code,d.name,d.kind,h.revision||'',h.issued?.toISOString().slice(0,10)||'',s.file,s.sheet,s.start_row]});download('danh_muc_xem_truoc.csv',csv(['Mã','Tên','Loại','Lần BH','Ngày BH','File','Sheet','Dòng'],rows),'text/csv;charset=utf-8')}
function exportIssues(){download('loi_danh_muc.csv',csv(['Mức','File','Sheet','Ô','Mã','Nội dung'],state.issues.map(x=>[x.level,x.file,x.sheet,x.cell,x.code,x.message])),'text/csv;charset=utf-8')}
$('addFiles').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>addFiles([...e.target.files]);$('selectAll').onclick=()=>{state.files.forEach(f=>f.sheets.forEach(s=>s.checked=true));renderFiles()};$('clearAll').onclick=()=>{state.files.forEach(f=>f.sheets.forEach(s=>s.checked=false));renderFiles()};$('scan').onclick=scan;$('pivot').onchange=updateHint;$('search').oninput=renderAll;$('kind').onchange=renderAll;$('issueLevel').onchange=renderAll;$('exportIssues').onclick=exportIssues;$('exportCatalogCsv').onclick=exportCatalogCsv;$('catalogTable').onclick=e=>{let tr=e.target.closest('[data-doc]');if(tr){let d=state.docs[+tr.dataset.doc];$('detailText').textContent=`${d.code}\n${d.name}\n\n`+d.history.map(h=>`Lần ${h.revision||'?'} | ${h.issued?.toLocaleDateString('vi-VN')||'Ngày lỗi'} | ${h.detail}\n${h.source.file} / ${h.source.sheet} / ${h.source.cell}\nNguyên văn: ${h.raw}`).join('\n\n');$('detail').showModal()}};$('closeDetail').onclick=()=>$('detail').close();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});updateHint();log('Sẵn sàng. File được xử lý cục bộ trong trình duyệt.');
document.getElementById('exportCatalog').onclick=exportCatalog;
const _scanSheetWithFooterRule=scanSheet;scanSheet=function(f,s){let ws=f.wb.Sheets[s.name],rows=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''}),cut=rows.length;for(let i=0;i<rows.length;i++){if(!rows[i].some(v=>norm(v))||/^ngay\s+thang\s+nam$/.test(simple(rows[i].filter(v=>norm(v)).join(' ')))){cut=i;break}}if(cut<rows.length){let copy=XLSX.utils.aoa_to_sheet(rows.slice(0,cut));let clone={...f,wb:{...f.wb,Sheets:{...f.wb.Sheets,[s.name]:copy}}};return _scanSheetWithFooterRule(clone,s)}return _scanSheetWithFooterRule(f,s)};
setTimeout(()=>{const originalScanSheet=scanSheet;scanSheet=(f,s)=>{let ws=f.wb.Sheets[s.name],rows=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''}),header=rows.findIndex(r=>simple(r[1]).includes('ten tai lieu')&&simple(r[2]).includes('ma so'));if(header>=0&&!rows[header].some(v=>simple(v).includes('ghi chu'))){let copy=rows.map(r=>r.slice());copy[header][Math.max(copy[header].length,7)]='Ghi chú';let clone={...f,wb:{...f.wb,Sheets:{...f.wb.Sheets,[s.name]:XLSX.utils.aoa_to_sheet(copy)}}};return originalScanSheet(clone,s)}return originalScanSheet(f,s)}},0);
setTimeout(()=>{scanSheet=(f,s)=>{let ws=f.wb.Sheets[s.name],rows=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''}),header=rows.findIndex(r=>simple(r[1]).includes('ten tai lieu')&&simple(r[2]).includes('ma so'));if(header<0)return _scanSheetWithFooterRule(f,s);let seenCode=false,cut=rows.length;for(let i=header+1;i<rows.length;i++){let r=rows[i],has=r.some(v=>norm(v)),code=norm(r[2]);if(code)seenCode=true;if(seenCode&&(!has||/ngay.*thang.*nam/.test(simple(r.filter(v=>norm(v)).join(' '))))){cut=i;break}}if(cut<rows.length){let copy=rows.slice(0,cut).map(r=>r.slice());let clone={...f,wb:{...f.wb,Sheets:{...f.wb.Sheets,[s.name]:XLSX.utils.aoa_to_sheet(copy)}}};return _scanSheetWithFooterRule(clone,s)}return _scanSheetWithFooterRule(f,s)}},0);
setTimeout(()=>{const baseScan=scanSheet;scanSheet=(f,s)=>{let ws=f.wb.Sheets[s.name],rows=XLSX.utils.sheet_to_json(ws,{header:1,raw:false,defval:''}),header=rows.findIndex(r=>simple(r[1]).includes('ten tai lieu')&&simple(r[2]).includes('ma so'));if(header<0)return baseScan(f,s);let cut=rows.length,seen=false;for(let i=header+1;i<rows.length;i++){let r=rows[i],text=simple(r.filter(v=>norm(v)).join(' '));if(norm(r[2]))seen=true;if(/ngay.*thang.*nam/.test(text)){cut=i;break}if(seen&&!r.some(v=>norm(v))){cut=i;break}}if(cut<rows.length){let copy=rows.slice(0,cut).map(r=>r.slice());let clone={...f,wb:{...f.wb,Sheets:{...f.wb.Sheets,[s.name]:XLSX.utils.aoa_to_sheet(copy)}}};return _scanSheetWithFooterRule(clone,s)}return _scanSheetWithFooterRule(f,s)}},50);
function exportIssuesXlsx(){let rows=state.issues.map(x=>[x.level,x.file,x.sheet,x.cell,x.code,x.message]),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Mức','File','Sheet','Ô','Mã','Nội dung'],...rows]),'Lỗi & cảnh báo');download('loi_danh_muc.xlsx',XLSX.write(wb,{bookType:'xlsx',type:'array'}),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}
setTimeout(()=>{let b=document.getElementById('exportIssuesXlsx');if(b){document.querySelector('#issues .toolbar').appendChild(b);b.style.display='';b.onclick=exportIssuesXlsx}},0);

